-- Track Section
CREATE TABLE TrackSection(
  Name VARCHAR(255) PRIMARY KEY NOT NULL,
  ElectricTracks BOOL,
  StartStation VARCHAR(255) NOT NULL, 
  EndStation VARCHAR(255) NOT NULL, 
  FOREIGN KEY(StartStation) REFERENCES RailwayStation(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(EndStation) REFERENCES RailwayStation(Name) ON UPDATE CASCADE ON DELETE CASCADE
);

 -- RailwayStation
CREATE TABLE RailwayStation(
  Name VARCHAR(255) PRIMARY KEY NOT NULL, 
  Height DOUBLE NOT NULL
); 

-- TrackSubSection
CREATE TABLE TrackSubSection(
  SubSectionNo INT NOT NULL, 
  SectionName VARCHAR(255) NOT NULL, 
  Distance INT, 
  DoubleTrack BOOL,  
  StartsAt VARCHAR(255) NOT NULL,
  EndsAt VARCHAR(255) NOT NULL, 
  FOREIGN KEY(StartsAt) REFERENCES Station(Name) ON UPDATE CASCADE ON DELETE CASCADE, 
  FOREIGN KEY(EndsAT) REFERENCES Station(Name) ON UPDATE CASCADE ON DELETE CASCADE, 
  FOREIGN KEY(SectionName) REFERENCES TrackSection(name) ON UPDATE CASCADE ON DELETE CASCADE,  
  CONSTRAINT PK_TrackSubSection PRIMARY KEY (SubSectionNo, SectionName)
);

--  TrainRoute    
CREATE TABLE TrainRoute(
  Name VARCHAR(255) PRIMARY KEY NOT NULL, 
  Operator VARCHAR(255), 
  SectionName VARCHAR(255) NOT NULL, 
  FOREIGN KEY(SectionName) REFERENCES TrackSection(Name) ON UPDATE CASCADE ON DELETE CASCADE
);

-- WeekDay
CREATE TABLE WeekDay(
  Name VARCHAR(255) PRIMARY KEY NOT NULL
);

-- Day of Route
CREATE TABLE DayOfRoute(
  NameOfDay VARCHAR(255) NOT NULL,
  NameOfRoute VARCHAR(255) NOT NULL,
  FOREIGN KEY (NameOfDay ) REFERENCES WeekDay(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (NameOfRoute) REFERENCES TrainRoute(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_DayOfRoute PRIMARY KEY(NameOfDay, NameOfRoute)
);

-- RouteStop
CREATE TABLE RouteStop( 
  Station VARCHAR(255) NOT NULL, 
  NameOfRoute VARCHAR(255) NOT NULL,
  TimeOfDay TIME,
  FOREIGN KEY(Station) REFERENCES RailwayStation(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(NameOfRoute) REFERENCES TrainRoute(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_RouteStop PRIMARY KEY(Station, NameOfRoute)
);

-- TrainOccurance
CREATE TABLE TrainOccurance(
  RunDate DATE NOT NULL,
  NameOfRoute VARCHAR(255) NOT NULL, 
  FOREIGN KEY(NameOfRoute) REFERENCES TrainRoute(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_TrainOccurance PRIMARY KEY(RunDate, NameOfRoute)
);

-- Placement
CREATE TABLE Placement(
  PlaceNo INT NOT NULL,
  CarID INT NOT NULL,
  FOREIGN KEY (CarID) REFERENCES CarInTrain(CarID) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_Placement PRIMARY KEY (PlaceNo, CarID)
);

-- CarInTrain
CREATE TABLE CarInTrain(
  CarID INT PRIMARY KEY NOT NULL, 
  CarNo INT,
  NameOfRoute, -- Denne ble ikke dokumentert i DB1
  FOREIGN KEY (NameOfRoute) REFERENCES TrainRoute(Name) ON UPDATE CASCADE ON DELETE CASCADE
);

-- ChairCar 
CREATE TABLE ChairCar(
  CarID INT NOT NULL,
  NumOfRows INT, 
  SeatsPerRow INT,
  PRIMARY KEY(CarID), 
  FOREIGN KEY (CarID) REFERENCES CarInTrain(CarID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- SleepCar 
CREATE TABLE SleepCar(
  CarID INT NOT NULL, 
  NumOfCompartments INT,
  PRIMARY KEY (CarID),
  FOREIGN KEY (CarID) REFERENCES CarInTrain(CarID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Ticket
CREATE TABLE Ticket(
  TicketNo INTEGER PRIMARY KEY AUTOINCREMENT, -- CHANGED AFTER DB1,
  OrderID INT NOT NULL,
  CarID INT NOT NULL,
  PlaceNo INT NOT NULL,
  NameOfRoute VARCHAR(255) NOT NULL,
  StartStation VARCHAR(255) NOT NULL, -- CHANGED AFTER DB1
  EndStation VARCHAR(255) NOT NULL, -- CHANGED AFTER DB1
  RunDate DATE NOT NULL,-- REDIGERT ETTER DB1
  FOREIGN KEY(NameOfRoute, RunDate) REFERENCES TrainOccurance(NameOfRoute, RunDate) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(OrderID) REFERENCES CustomerOrder(OrderID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(CarID, PlaceNo) REFERENCES  Placement(CarID, PlaceNo) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE (TicketNo, OrderID)
  -- CONSTRAINT PK_Ticket PRIMARY KEY (TicketNo, OrderID)
);

-- CustomerOrder
CREATE TABLE CustomerOrder(
  OrderID INTEGER PRIMARY KEY AUTOINCREMENT, -- CHANGED AFTER DB1,
  OrderDate DATE NOT NULL,
  OrderTime INT NOT NULL,
  CustomerID INT NOT NULL,
  FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Customer
CREATE TABLE Customer(
  CustomerID INTEGER PRIMARY KEY AUTOINCREMENT, -- CHANGED AFTER DB1
  Name VARCHAR(255) NOT NULL, 
  Email VARCHAR(255) NOT NULL, 
  PhoneNO INT NOT NULL
);

CREATE TABLE TicketOnSection( -- Ny entitet
  TicketNo INT NOT NULL,
  StartStation VARCHAR(255) NOT NULL, 
  EndStation VARCHAR(255) NOT NULL,
  FOREIGN KEY(TicketNo) REFERENCES Ticket(TicketNo) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(StartStation) REFERENCES TrackSubSection(StartsAt) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(EndStation) REFERENCES TrackSubSection(EndsAt) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_TicketOnSection PRIMARY KEY (TicketNo, StartStation, EndStation)
);
