-- Track Section
CREATE TABLE TrackSection(
  Name VARCHAR(255) PRIMARY KEY NOT NULL,
  ElectricTracks BOOL,
  StartStation VARCHAR(255) NOT NULL, 
  EndStation VARCHAR(255) NOT NULL, 
  FOREIGN KEY(StartStation) REFERENCES RailwayStation(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(EndStation) REFERENCES RailwayStation(Name) ON UPDATE CASCADE ON DELETE CASCADE
);

 -- RailwayStation
CREATE TABLE RailwayStation(
  Name VARCHAR(255) PRIMARY KEY NOT NULL, 
  Height DOUBLE NOT NULL
); 

-- TrackSubSection
CREATE TABLE TrackSubSection(
  SubSectionNo INT NOT NULL, 
  SectionName VARCHAR(255) NOT NULL, 
  Distance INT, 
  DoubleTrack BOOL,  
  StartsAt VARCHAR(255) NOT NULL,
  EndsAt VARCHAR(255) NOT NULL, 
  FOREIGN KEY(StartsAt) REFERENCES Station(Name) ON UPDATE CASCADE ON DELETE CASCADE, 
  FOREIGN KEY(EndsAT) REFERENCES Station(Name) ON UPDATE CASCADE ON DELETE CASCADE, 
  FOREIGN KEY(SectionName) REFERENCES TrackSection(name) ON UPDATE CASCADE ON DELETE CASCADE,  
  CONSTRAINT PK_TrackSubSection PRIMARY KEY (SubSectionNo, SectionName)
);

--  TrainRoute    
CREATE TABLE TrainRoute(
  Name VARCHAR(255) PRIMARY KEY NOT NULL, 
  Operator VARCHAR(255), 
  SectionName VARCHAR(255) NOT NULL, 
  FOREIGN KEY(SectionName) REFERENCES TrackSection(Name) ON UPDATE CASCADE ON DELETE CASCADE
);

-- WeekDay
CREATE TABLE WeekDay(
  Name VARCHAR(255) PRIMARY KEY NOT NULL
);

-- Day of Route
CREATE TABLE DayOfRoute(
  NameOfDay VARCHAR(255) NOT NULL,
  NameOfRoute VARCHAR(255) NOT NULL,
  FOREIGN KEY (NameOfDay ) REFERENCES WeekDay(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (NameOfRoute) REFERENCES TrainRoute(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_DayOfRoute PRIMARY KEY(NameOfDay, NameOfRoute)
);

-- RouteStop
CREATE TABLE RouteStop( 
  Station VARCHAR(255) NOT NULL, 
  NameOfRoute VARCHAR(255) NOT NULL,
  TimeOfDay TIME,
  FOREIGN KEY(Station) REFERENCES RailwayStation(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(NameOfRoute) REFERENCES TrainRoute(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_RouteStop PRIMARY KEY(Station, NameOfRoute)
);

-- TrainOccurance
CREATE TABLE TrainOccurance(
  RunDate DATE NOT NULL,
  NameOfRoute VARCHAR(255) NOT NULL, 
  FOREIGN KEY(NameOfRoute) REFERENCES TrainRoute(Name) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_TrainOccurance PRIMARY KEY(RunDate, NameOfRoute)
);

-- Placement
CREATE TABLE Placement(
  PlaceNo INT NOT NULL,
  CarID INT NOT NULL,
  FOREIGN KEY (CarID) REFERENCES CarInTrain(CarID) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_Placement PRIMARY KEY (PlaceNo, CarID)
);

-- CarInTrain
CREATE TABLE CarInTrain(
  CarID INT PRIMARY KEY NOT NULL, 
  CarNo INT
);

-- ChairCar 
CREATE TABLE ChairCar(
  CarID INT NOT NULL,
  NumOfRows INT, 
  SeatsPerRow INT,
  PRIMARY KEY(CarID), 
  FOREIGN KEY (CarID) REFERENCES CarInTrain(CarID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- SleepCar 
CREATE TABLE SleepCar(
  CarID INT NOT NULL, 
  NumOfCompartments INT,
  PRIMARY KEY (CarID),
  FOREIGN KEY (CarID) REFERENCES CarInTrain(CarID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Ticket
CREATE TABLE Ticket(
  TicketNo INT AUTO_INCREMENT NOT NULL,
  OrderID INT NOT NULL,
  CarID INT NOT NULL,
  PlaceNo INT NOT NULL,
  FOREIGN KEY(OrderID) REFERENCES CustomerOrder(OrderID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(CarID, PlaceNo) REFERENCES  Placement(CarID, PlaceNo) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT PK_Ticket PRIMARY KEY (TicketNo, OrderID)
);

-- CustomerOrder
CREATE TABLE CustomerOrder(
  OrderID INT NOT NULL,
  OrderDate DATE NOT NULL,
  OrderTime INT NOT NULL,
  CustomerID INT NOT NULL,
  PRIMARY KEY (OrderID),
  FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- Customer
CREATE TABLE Customer(
  CustomerID INT NOT NULL, 
  Name VARCHAR(255) NOT NULL, 
  Email VARCHAR(255) NOT NULL, 
  PhoneNO INT NOT NULL, 
  RegistryID INT NOT NULL, 
  PRIMARY KEY (CustomerID, RegistryID),
  FOREIGN KEY(RegistryID) REFERENCES CustomerRegistry(RegistryID) ON UPDATE CASCADE ON DELETE CASCADE
);

-- CustomerRegistry
CREATE TABLE CustomerRegistry(
  RegistryID INT NOT NULL,
  PRIMARY KEY (RegistryID)
);


